question_visibility_simple = (
    "You are shown two identical images from a head-mounted camera:\n"
    "- Image 1 is the original camera view.\n"
    "- Image 2 is the same view but with a UI element overlayed on part of the scene.\n"
    "\n"
    "Determine whether the UI element should be kept or removed. "
    "The UI element should be removed if it covers what the user is using, about to use, or interacting with, "
    "floor, doors, windows or signs, people's faces or bodies, or areas of high colour intensity or edge contrast. "
    "Otherwise, it should be kept.\n"
    "\n"
    "FINAL ANSWER: [Yes, keep the element | No, remove the element]"
)


question_visibility_structured = (
    "You are shown two identical images from a head‑mounted camera:\n"
    "- Image 1 is the original camera view.\n"
    "- Image 2 is the same view but with a UI element overlayed on part of the scene.\n"
    "\n"
    "Step 1: What does the UI element cover?\n"
    "'Covers' means the element hides part of an object from view. If the object is fully visible around the element, it is not covered.\n"
    "Answer format: The element covers [object/area].\n"
    "\n"
    "Step 2: Answer each question with 'yes' or 'no':\n"
    "- Does the element cover something the user is using, about to use, or interacting with?\n"
    "- Does the element cover the floor, doors, windows or signs?\n"
    "- Does the element cover people's faces or bodies?\n"
    "- Does the element cover an area of high colour intensity or edge contrast?\n"
    "IMPORTANT RULE:\n"
    "- If **any** answer in Step 2 is 'yes' → FINAL ANSWER: No, remove the element.\n"
    "- If **all** answers in Step 2 are 'no' → FINAL ANSWER: Yes, keep the element.\n"
    "\n"
    "STRICT FORMAT:\n"
    "Step 1: [Your answer here]\n"
    "Step 2:\n"
    "- Covers floor/doors/windows/signs: [yes/no]\n"
    "- Covers people: [yes/no]\n"
    "- Covers high‑contrast or high‑colour‑intensity area: [yes/no]\n"
    "FINAL ANSWER: [Yes, keep the element | No, remove the element]"
)


question_visibility_structured_with_few_shot = (
    "You are shown two identical images from a head‑mounted camera:\n"
    "- Image 1 is the original camera view.\n"
    "- Image 2 is the same view but with a UI element overlayed on part of the scene.\n"
    "\n"
    "Step 1: What does the UI element cover?\n"
    "'Covers' means the element hides part of an object from view. If the object is fully visible around the element, it is not covered.\n"
    "Answer format: The element covers [object/area].\n"
    "\n"
    "Step 2: Answer each question with 'yes' or 'no':\n"
    "- Does the element cover something the user is using, about to use, or interacting with?\n"
    "- Does the element cover the floor, doors, windows or signs?\n"
    "- Does the element cover people's faces or bodies?\n"
    "- Does the element cover an area of high colour intensity or edge contrast?\n"
    "\n"
    "IMPORTANT RULE:\n"
    "- If **any** answer in Step 2 is 'yes' → FINAL ANSWER: No, remove the element.\n"
    "- If **all** answers in Step 2 are 'no' → FINAL ANSWER: Yes, keep the element.\n"
    "\n"
    "STRICT FORMAT:\n"
    "Step 1: [Your answer here]\n"
    "Step 2:\n"
    "- Covers user interaction objects: [yes/no]\n"
    "- Covers floor/doors/windows/signs: [yes/no]\n"
    "- Covers people: [yes/no]\n"
    "- Covers high‑contrast or high‑colour‑intensity area: [yes/no]\n"
    "FINAL ANSWER: [Yes, keep the element | No, remove the element]\n"
    "\n"
    "Example answer:\n"
    "Step 1: The element covers part of a door handle.\n"
    "Step 2:\n"
    "- Covers user interaction objects: yes\n"
    "- Covers floor/doors/windows/signs: yes\n"
    "- Covers people: no\n"
    "- Covers high‑contrast or high‑colour‑intensity area: no\n"
    "FINAL ANSWER: No, remove the element."
)

question_placement_structured = (
    "You are shown three identical images from a head-mounted camera:\n"
    "- Image 1 is the original camera view.\n"
    "- Image 2 is the same view with a UI element overlayed in one part of the scene.\n"
    "- Image 3 is the same view with a UI element overlayed in a different part of the scene.\n"
    "\n"
    "Step 1: What do the UI elements in Image 2 and Image 3 cover?\n"
    "An element 'covers' an object if it hides any part of it from view. If the object is fully visible around the element, it is not considered covered.\n"
    "Answer format: In Image 2, the element covers [object/area]. In Image 3, the element covers [object/area].\n"
    "\n"
    "Step 2: For each image, answer the following four yes/no questions about the UI element in that image:\n"
    "1. Does the element cover something the user is using, about to use, or interacting with?\n"
    "2. Does the element cover the floor, doors, windows, or signs?\n"
    "3. Does the element cover people's faces or bodies?\n"
    "4. Does the element cover an area of high colour intensity or edge contrast?\n"
    "\n"
    "Then, compare the total number of 'yes' answers between the two images.\n"
    "- If Image 2 has fewer 'yes' answers, answer 1 (left).\n"
    "- If Image 3 has fewer 'yes' answers, answer 2 (right).\n"
    "\n"
    "STRICT FORMAT:\n"
    "Step 1: In Image 2, the element covers [...]. In Image 3, the element covers [...].\n"
    "Step 2 (Image 2):\n"
    "- Covers something used/interacted with: [yes/no]\n"
    "- Covers floor/doors/windows/signs: [yes/no]\n"
    "- Covers people: [yes/no]\n"
    "- Covers high-contrast or high-colour-intensity area: [yes/no]\n"
    "Step 2 (Image 3):\n"
    "- Covers something used/interacted with: [yes/no]\n"
    "- Covers floor/doors/windows/signs: [yes/no]\n"
    "- Covers people: [yes/no]\n"
    "- Covers high-contrast or high-colour-intensity area: [yes/no]\n"
    "FINAL ANSWER: [1 | 2]"
)


# Test with new prompt to achieve the generalization task (placement via visibilty)
question_placement_via_visibility = (
    "System: You are a precise visual judge. Be concise and structured. Do not explain your reasoning.\n"
    "User: You see THREE images:\n"
    "- Image 1: original view (reference).\n"
    "- Image 2: original + UI overlay at position A.\n"
    "- Image 3: original + UI overlay at position B.\n"
    "\n"
    "Task:\n"
    "- Evaluate KEEP? for Image 2 relative to Image 1.\n"
    "- Evaluate KEEP? for Image 3 relative to Image 1.\n"
    "Criteria (apply equally to both): avoid occluding (1) things the user is using/about to use, "
    "(2) floor/doors/windows/signs, (3) people, (4) areas with strong edges/colors.\n"
    "\n"
    "FORMAT EXACTLY:\n"
    "I2-KEEP: [Yes|No]\n"
    "I3-KEEP: [Yes|No]\n"
    "FINAL: [1|2]   # 1 = choose Image 2, 2 = choose Image 3. "
    "If both are acceptable, choose the one that occludes fewer important categories overall; if indistinguishable, pick 2.\n"
)

